name: fmi-py
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - anyio=4.11.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - assimulo=3.7.2
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.4.0
  - aws-c-auth=0.9.1
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.22.0
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.4
  - aws-sdk-cpp=1.11.606
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blinker=1.9.0
  - bokeh=3.8.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.3
  - choreographer=1.1.2
  - click=8.3.0
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cycler=0.12.1
  - cytoolz=1.0.1
  - dash=3.2.0
  - dash-bootstrap-components=2.0.4
  - dask=2025.9.1
  - dask-core=2025.9.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - distributed=2025.9.1
  - double-conversion=3.3.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - flask=3.1.2
  - fmilib=3.0.4
  - fmpy=0.3.19
  - fmpy-base=0.3.19
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - fsspec=2025.9.0
  - glib=2.86.0
  - glib-tools=2.86.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=12.1.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.9
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.0
  - lark-parser=0.12.0
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libamd=3.3.3
  - libarrow=21.0.0
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libbtf=2.3.2
  - libcamd=3.3.3
  - libcblas=3.9.0
  - libccolamd=3.3.4
  - libcholmod=5.3.1
  - libclang13=21.1.2
  - libcolamd=3.3.4
  - libcrc32c=1.1.2
  - libcurl=8.14.1
  - libcxsparse=4.4.1
  - libdeflate=1.24
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libglib=2.86.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.1.0
  - libklu=2.3.5
  - liblapack=3.9.0
  - libldl=3.3.2
  - liblzma=5.8.1
  - libogg=1.3.5
  - libparquet=21.0.0
  - libparu=1.0.0
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - librbio=4.3.4
  - libre2-11=2025.08.12
  - libsodium=1.0.20
  - libspex=3.2.3
  - libspqr=4.3.4
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libsuitesparseconfig=7.10.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libumfpack=6.3.5
  - libutf8proc=2.11.0
  - libvorbis=1.3.7
  - libvulkan-loader=1.4.328.1
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.15.0
  - libxml2-16=2.15.0
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.2
  - locket=1.0.0
  - logistro=1.1.0
  - lxml=6.0.2
  - lz4=4.4.4
  - lz4-c=1.10.0
  - markupsafe=3.0.3
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - metis=5.1.0
  - minizip=4.0.10
  - mistune=3.1.4
  - mkl=2024.2.2
  - mpfr=4.2.1
  - msgpack-python=1.1.2
  - munkres=1.1.4
  - narwhals=2.7.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook=7.4.7
  - notebook-shim=0.2.4
  - numpy=2.3.3
  - openjpeg=2.5.4
  - openssl=3.5.4
  - orc=2.2.1
  - orjson=3.11.3
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - parso=0.8.5
  - partd=1.4.2
  - pathlib=1.0.1
  - pcre2=10.46
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - plotly=6.3.1
  - ply=3.11
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.0
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pyarrow=21.0.0
  - pyarrow-core=21.0.0
  - pycparser=2.22
  - pyfmi=2.18.3
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pyqtgraph=0.13.7
  - pyqtwebengine=5.15.11
  - pyside6=6.9.3
  - pysocks=1.7.1
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-kaleido=1.0.0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pywin32=311
  - pywinpty=2.0.15
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt-main=5.15.15
  - qt-webengine=5.15.15
  - qt6-main=6.9.3
  - re2=2025.08.12
  - referencing=0.36.2
  - requests=2.32.5
  - retrying=1.4.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.27.1
  - scipy=1.16.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - simplejson=3.20.2
  - sip=6.10.0
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.8
  - stack_data=0.6.3
  - suitesparse=7.10.1
  - sundials=7.4.0
  - tbb=2021.13.0
  - tblib=3.1.0
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.3.0
  - toolz=1.0.0
  - tornado=6.5.2
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20251008
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.4.0
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.23.0
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - flatbuffers==25.9.23
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - keras==3.12.0
      - libclang==18.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - namex==0.1.0
      - opt-einsum==3.4.0
      - optree==0.18.0
      - protobuf==6.33.1
      - rich==14.2.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.2.0
      - wrapt==2.0.1
prefix: C:\Users\ADMIN\anaconda3\envs\fmi-py
